server:
  port: 8081
  mode: debug

database:
  driver: memory
  host: localhost
  port: 3306
  username: root
  password: "123456"
  dbname: ":memory:"
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expire: "24h"

# 日志配置
log:
  level: info
  format: json
  output: stdout

# 文件上传配置
upload:
  max_size: 10MB
  allowed_types:
    - image/jpeg
    - image/png
    - image/gif
  upload_path: "./uploads"
