server:
  port: 8081
  mode: debug

database:
  driver: sqlite
  host: localhost
  port: 3306
  username: root
  password: "123456"
  dbname: ./mall_go.db
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: "123456"
  db: 0
  # 连接池配置优化 - 生产环境推荐配置
  pool_size: 200          # 连接池大小，支持更高并发
  min_idle_conns: 20      # 最小空闲连接数，保证快速响应
  max_retries: 5          # 最大重试次数，提高容错性
  dial_timeout: 10        # 连接超时时间(秒)，适应网络延迟
  read_timeout: 5         # 读取超时时间(秒)，平衡性能和稳定性
  write_timeout: 5        # 写入超时时间(秒)，平衡性能和稳定性
  idle_timeout: 600       # 空闲连接超时时间(秒)，10分钟
  max_conn_age: 7200      # 连接最大存活时间(秒)，2小时
  # 性能优化配置
  pool_timeout: 30        # 获取连接超时时间(秒)
  idle_check_frequency: 60 # 空闲连接检查频率(秒)
  max_redirect: 8         # 集群模式最大重定向次数
  read_only: false        # 是否只读模式
  route_by_latency: true  # 按延迟路由(集群模式)
  route_randomly: false   # 随机路由(集群模式)

jwt:
  secret: "your-secret-key-change-in-production"
  expire: "24h"

# 日志配置
log:
  level: info
  format: json
  output: stdout

# 文件上传配置
upload:
  max_size: 10MB
  allowed_types:
    - image/jpeg
    - image/png
    - image/gif
  upload_path: "./uploads"
