-- Mall Go 数据库表结构
-- 创建时间: 2024-08-31
-- 数据库: gomall

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- 用户表
-- ----------------------------
DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `NICKNAME` VARCHAR(50) DEFAULT NULL,
  `AVATAR` VARCHAR(255) DEFAULT NULL,
  `PHONE` VARCHAR(20) DEFAULT NULL,
  `ROLE` VARCHAR(20) DEFAULT 'user',
  `STATUS` VARCHAR(20) DEFAULT 'active',
  `REAL_NAME` VARCHAR(50) DEFAULT NULL,
  `GENDER` VARCHAR(10) DEFAULT 'unknown',
  `BIRTHDAY` DATETIME(3) DEFAULT NULL,
  `BIO` VARCHAR(500) DEFAULT NULL,
  `LOCATION` VARCHAR(100) DEFAULT NULL,
  `WEBSITE` VARCHAR(255) DEFAULT NULL,
  `EMAIL_VERIFIED` TINYINT(1) DEFAULT '0',
  `PHONE_VERIFIED` TINYINT(1) DEFAULT '0',
  `EMAIL_VERIFIED_AT` DATETIME(3) DEFAULT NULL,
  `PHONE_VERIFIED_AT` DATETIME(3) DEFAULT NULL,
  `LAST_LOGIN_AT` DATETIME(3) DEFAULT NULL,
  `LAST_LOGIN_IP` VARCHAR(45) DEFAULT NULL,
  `LOGIN_ATTEMPTS` BIGINT DEFAULT '0',
  `LOCKED_UNTIL` DATETIME(3) DEFAULT NULL,
  `PASSWORD_CHANGED_AT` DATETIME(3) DEFAULT NULL,
  `TWO_FACTOR_ENABLED` TINYINT(1) DEFAULT '0',
  `TWO_FACTOR_SECRET` VARCHAR(32) DEFAULT NULL,
  `LOGIN_COUNT` BIGINT DEFAULT '0',
  `POST_COUNT` BIGINT DEFAULT '0',
  `FOLLOWER_COUNT` BIGINT DEFAULT '0',
  `FOLLOWING_COUNT` BIGINT DEFAULT '0',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_USERS_USERNAME` (`USERNAME`),
  UNIQUE KEY `IDX_USERS_EMAIL` (`EMAIL`),
  UNIQUE KEY `IDX_USERS_PHONE` (`PHONE`),
  KEY `IDX_USERS_ROLE` (`ROLE`),
  KEY `IDX_USERS_STATUS` (`STATUS`),
  KEY `IDX_USERS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 用户资料表
-- ----------------------------
DROP TABLE IF EXISTS `USER_PROFILES`;

CREATE TABLE `USER_PROFILES` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `COMPANY` VARCHAR(100) DEFAULT NULL,
  `POSITION` VARCHAR(50) DEFAULT NULL,
  `EDUCATION` VARCHAR(50) DEFAULT NULL,
  `EXPERIENCE` VARCHAR(20) DEFAULT NULL,
  `SKILLS` JSON DEFAULT NULL,
  `INTERESTS` JSON DEFAULT NULL,
  `SOCIAL_LINKS` JSON DEFAULT NULL,
  `LANGUAGE` VARCHAR(10) DEFAULT 'zh-CN',
  `TIMEZONE` VARCHAR(50) DEFAULT 'Asia/Shanghai',
  `THEME` VARCHAR(20) DEFAULT 'light',
  `EMAIL_NOTIFY` TINYINT(1) DEFAULT '1',
  `SMS_NOTIFY` TINYINT(1) DEFAULT '0',
  `PUSH_NOTIFY` TINYINT(1) DEFAULT '1',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_USER_PROFILES_USER_ID` (`USER_ID`),
  KEY `IDX_USER_PROFILES_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 分类表
-- ----------------------------
DROP TABLE IF EXISTS `CATEGORIES`;

CREATE TABLE `CATEGORIES` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `SLUG` VARCHAR(100) NOT NULL,
  `DESCRIPTION` TEXT,
  `IMAGE` VARCHAR(500) DEFAULT NULL,
  `ICON` VARCHAR(100) DEFAULT NULL,
  `PARENT_ID` BIGINT UNSIGNED DEFAULT '0',
  `LEVEL` INT DEFAULT '1',
  `PATH` VARCHAR(500) DEFAULT NULL,
  `SORT_ORDER` INT DEFAULT '0',
  `IS_ACTIVE` TINYINT(1) DEFAULT '1',
  `SEO_TITLE` VARCHAR(200) DEFAULT NULL,
  `SEO_DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `SEO_KEYWORDS` VARCHAR(500) DEFAULT NULL,
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_CATEGORIES_SLUG` (`SLUG`),
  KEY `IDX_CATEGORIES_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_CATEGORIES_LEVEL` (`LEVEL`),
  KEY `IDX_CATEGORIES_SORT_ORDER` (`SORT_ORDER`),
  KEY `IDX_CATEGORIES_IS_ACTIVE` (`IS_ACTIVE`),
  KEY `IDX_CATEGORIES_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 商品表
-- ----------------------------
DROP TABLE IF EXISTS `PRODUCTS`;

CREATE TABLE `PRODUCTS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `SUB_TITLE` VARCHAR(500) DEFAULT NULL,
  `DESCRIPTION` TEXT,
  `DETAIL` LONGTEXT,
  `CATEGORY_ID` BIGINT UNSIGNED NOT NULL,
  `BRAND_ID` BIGINT UNSIGNED DEFAULT NULL,
  `MERCHANT_ID` BIGINT UNSIGNED NOT NULL,
  `PRICE` DECIMAL(10, 2) NOT NULL,
  `ORIGIN_PRICE` DECIMAL(10, 2) DEFAULT NULL,
  `COST_PRICE` DECIMAL(10, 2) DEFAULT NULL,
  `STOCK` INT NOT NULL DEFAULT '0',
  `MIN_STOCK` INT DEFAULT '0',
  `MAX_STOCK` INT DEFAULT '0',
  `SOLD_COUNT` INT DEFAULT '0',
  `VERSION` INT NOT NULL DEFAULT '0',
  `WEIGHT` DECIMAL(8, 3) DEFAULT NULL,
  `VOLUME` DECIMAL(8, 3) DEFAULT NULL,
  `UNIT` VARCHAR(20) DEFAULT NULL,
  `STATUS` VARCHAR(20) DEFAULT 'draft',
  `IS_HOT` TINYINT(1) DEFAULT '0',
  `IS_NEW` TINYINT(1) DEFAULT '0',
  `IS_RECOMMEND` TINYINT(1) DEFAULT '0',
  `IS_VIRTUAL` TINYINT(1) DEFAULT '0',
  `VIRTUAL_TYPE` VARCHAR(20) DEFAULT NULL,
  `VIRTUAL_CONTENT` TEXT,
  `TAGS` JSON DEFAULT NULL,
  `ATTRS` JSON DEFAULT NULL,
  `SEO_TITLE` VARCHAR(200) DEFAULT NULL,
  `SEO_DESCRIPTION` VARCHAR(500) DEFAULT NULL,
  `SEO_KEYWORDS` VARCHAR(500) DEFAULT NULL,
  `SORT_ORDER` INT DEFAULT '0',
  `VIEW_COUNT` BIGINT DEFAULT '0',
  `FAVORITE_COUNT` BIGINT DEFAULT '0',
  `COMMENT_COUNT` BIGINT DEFAULT '0',
  `RATING` DECIMAL(3, 2) DEFAULT '0.00',
  `RATING_COUNT` BIGINT DEFAULT '0',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PRODUCTS_NAME` (`NAME`),
  KEY `IDX_PRODUCTS_CATEGORY_ID` (`CATEGORY_ID`),
  KEY `IDX_PRODUCTS_BRAND_ID` (`BRAND_ID`),
  KEY `IDX_PRODUCTS_MERCHANT_ID` (`MERCHANT_ID`),
  KEY `IDX_PRODUCTS_STATUS` (`STATUS`),
  KEY `IDX_PRODUCTS_IS_HOT` (`IS_HOT`),
  KEY `IDX_PRODUCTS_IS_NEW` (`IS_NEW`),
  KEY `IDX_PRODUCTS_IS_RECOMMEND` (`IS_RECOMMEND`),
  KEY `IDX_PRODUCTS_SORT_ORDER` (`SORT_ORDER`),
  KEY `IDX_PRODUCTS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 商品图片表
-- ----------------------------
DROP TABLE IF EXISTS `PRODUCT_IMAGES`;

CREATE TABLE `PRODUCT_IMAGES` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` BIGINT UNSIGNED NOT NULL,
  `URL` VARCHAR(500) NOT NULL,
  `ALT` VARCHAR(200) DEFAULT NULL,
  `TITLE` VARCHAR(200) DEFAULT NULL,
  `IS_MAIN` TINYINT(1) DEFAULT '0',
  `SORT_ORDER` INT DEFAULT '0',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PRODUCT_IMAGES_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `IDX_PRODUCT_IMAGES_IS_MAIN` (`IS_MAIN`),
  KEY `IDX_PRODUCT_IMAGES_SORT_ORDER` (`SORT_ORDER`),
  KEY `IDX_PRODUCT_IMAGES_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 商品SKU表
-- ----------------------------
DROP TABLE IF EXISTS `PRODUCT_SKUS`;

CREATE TABLE `PRODUCT_SKUS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` BIGINT UNSIGNED NOT NULL,
  `SKU_CODE` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `PRICE` DECIMAL(10, 2) NOT NULL,
  `STOCK` INT NOT NULL DEFAULT '0',
  `VERSION` INT NOT NULL DEFAULT '0',
  `IMAGE` VARCHAR(500) DEFAULT NULL,
  `WEIGHT` DECIMAL(8, 3) DEFAULT NULL,
  `VOLUME` DECIMAL(8, 3) DEFAULT NULL,
  `STATUS` VARCHAR(20) DEFAULT 'active',
  `ATTRIBUTES` JSON DEFAULT NULL,
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_PRODUCT_SKUS_SKU_CODE` (`SKU_CODE`),
  KEY `IDX_PRODUCT_SKUS_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `IDX_PRODUCT_SKUS_STATUS` (`STATUS`),
  KEY `IDX_PRODUCT_SKUS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 购物车表
-- ----------------------------
DROP TABLE IF EXISTS `CARTS`;

CREATE TABLE `CARTS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT UNSIGNED DEFAULT NULL,
  `SESSION_ID` VARCHAR(100) DEFAULT NULL,
  `STATUS` VARCHAR(20) DEFAULT 'active',
  `ITEM_COUNT` INT DEFAULT '0',
  `TOTAL_QTY` INT DEFAULT '0',
  `TOTAL_AMOUNT` DECIMAL(10, 2) DEFAULT '0.00',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CARTS_USER_ID` (`USER_ID`),
  KEY `IDX_CARTS_SESSION_ID` (`SESSION_ID`),
  KEY `IDX_CARTS_STATUS` (`STATUS`),
  KEY `IDX_CARTS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 购物车商品项表
-- ----------------------------
DROP TABLE IF EXISTS `CART_ITEMS`;

CREATE TABLE `CART_ITEMS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CART_ID` BIGINT UNSIGNED NOT NULL,
  `PRODUCT_ID` BIGINT UNSIGNED NOT NULL,
  `SKU_ID` BIGINT UNSIGNED DEFAULT NULL,
  `QUANTITY` INT NOT NULL DEFAULT '1',
  `PRICE` DECIMAL(10, 2) NOT NULL,
  `PRODUCT_NAME` VARCHAR(255) NOT NULL,
  `PRODUCT_IMAGE` VARCHAR(500) DEFAULT NULL,
  `SKU_NAME` VARCHAR(255) DEFAULT NULL,
  `SKU_IMAGE` VARCHAR(500) DEFAULT NULL,
  `SKU_ATTRS` JSON DEFAULT NULL,
  `SELECTED` TINYINT(1) DEFAULT '1',
  `STATUS` VARCHAR(20) DEFAULT 'normal',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CART_ITEMS_CART_ID` (`CART_ID`),
  KEY `IDX_CART_ITEMS_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `IDX_CART_ITEMS_SKU_ID` (`SKU_ID`),
  KEY `IDX_CART_ITEMS_STATUS` (`STATUS`),
  KEY `IDX_CART_ITEMS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 订单表
-- ----------------------------
DROP TABLE IF EXISTS `ORDERS`;

CREATE TABLE `ORDERS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ORDER_NO` VARCHAR(32) NOT NULL,
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `STATUS` VARCHAR(20) DEFAULT 'pending',
  `PAYMENT_STATUS` VARCHAR(20) DEFAULT 'unpaid',
  `SHIPPING_STATUS` VARCHAR(20) DEFAULT 'unshipped',
  `TOTAL_AMOUNT` DECIMAL(10, 2) NOT NULL,
  `PAYMENT_AMOUNT` DECIMAL(10, 2) DEFAULT '0.00',
  `SHIPPING_AMOUNT` DECIMAL(10, 2) DEFAULT '0.00',
  `DISCOUNT_AMOUNT` DECIMAL(10, 2) DEFAULT '0.00',
  `COUPON_AMOUNT` DECIMAL(10, 2) DEFAULT '0.00',
  `ITEM_COUNT` INT DEFAULT '0',
  `TOTAL_QTY` INT DEFAULT '0',
  `PAYMENT_METHOD` VARCHAR(20) DEFAULT NULL,
  `PAYMENT_TIME` DATETIME(3) DEFAULT NULL,
  `SHIPPED_TIME` DATETIME(3) DEFAULT NULL,
  `DELIVERED_TIME` DATETIME(3) DEFAULT NULL,
  `FINISHED_TIME` DATETIME(3) DEFAULT NULL,
  `CANCELLED_TIME` DATETIME(3) DEFAULT NULL,
  `CANCEL_REASON` VARCHAR(200) DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  `SHIPPING_NAME` VARCHAR(50) DEFAULT NULL,
  `SHIPPING_PHONE` VARCHAR(20) DEFAULT NULL,
  `SHIPPING_ADDRESS` VARCHAR(500) DEFAULT NULL,
  `SHIPPING_PROVINCE` VARCHAR(50) DEFAULT NULL,
  `SHIPPING_CITY` VARCHAR(50) DEFAULT NULL,
  `SHIPPING_DISTRICT` VARCHAR(50) DEFAULT NULL,
  `SHIPPING_POSTCODE` VARCHAR(10) DEFAULT NULL,
  `TRACKING_NO` VARCHAR(100) DEFAULT NULL,
  `EXPRESS_COMPANY` VARCHAR(50) DEFAULT NULL,
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_ORDERS_ORDER_NO` (`ORDER_NO`),
  KEY `IDX_ORDERS_USER_ID` (`USER_ID`),
  KEY `IDX_ORDERS_STATUS` (`STATUS`),
  KEY `IDX_ORDERS_PAYMENT_STATUS` (`PAYMENT_STATUS`),
  KEY `IDX_ORDERS_SHIPPING_STATUS` (`SHIPPING_STATUS`),
  KEY `IDX_ORDERS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 订单商品项表
-- ----------------------------
DROP TABLE IF EXISTS `ORDER_ITEMS`;

CREATE TABLE `ORDER_ITEMS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ORDER_ID` BIGINT UNSIGNED NOT NULL,
  `PRODUCT_ID` BIGINT UNSIGNED NOT NULL,
  `SKU_ID` BIGINT UNSIGNED DEFAULT NULL,
  `PRODUCT_NAME` VARCHAR(255) NOT NULL,
  `PRODUCT_IMAGE` VARCHAR(500) DEFAULT NULL,
  `SKU_NAME` VARCHAR(255) DEFAULT NULL,
  `SKU_ATTRS` JSON DEFAULT NULL,
  `PRICE` DECIMAL(10, 2) NOT NULL,
  `QUANTITY` INT NOT NULL,
  `TOTAL_AMOUNT` DECIMAL(10, 2) NOT NULL,
  `REFUND_STATUS` VARCHAR(20) DEFAULT 'none',
  `REFUND_QUANTITY` INT DEFAULT '0',
  `REFUND_AMOUNT` DECIMAL(10, 2) DEFAULT '0.00',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_ORDER_ITEMS_ORDER_ID` (`ORDER_ID`),
  KEY `IDX_ORDER_ITEMS_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `IDX_ORDER_ITEMS_SKU_ID` (`SKU_ID`),
  KEY `IDX_ORDER_ITEMS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 支付表
-- ----------------------------
DROP TABLE IF EXISTS `PAYMENTS`;

CREATE TABLE `PAYMENTS` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PAYMENT_NO` VARCHAR(32) NOT NULL,
  `ORDER_ID` BIGINT UNSIGNED NOT NULL,
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `AMOUNT` DECIMAL(10, 2) NOT NULL,
  `CURRENCY` VARCHAR(3) DEFAULT 'CNY',
  `METHOD` VARCHAR(20) NOT NULL,
  `CHANNEL` VARCHAR(20) DEFAULT NULL,
  `STATUS` VARCHAR(20) DEFAULT 'pending',
  `TRANSACTION_ID` VARCHAR(100) DEFAULT NULL,
  `THIRD_PARTY_ID` VARCHAR(100) DEFAULT NULL,
  `CALLBACK_DATA` JSON DEFAULT NULL,
  `PAID_AT` DATETIME(3) DEFAULT NULL,
  `EXPIRED_AT` DATETIME(3) DEFAULT NULL,
  `REMARK` VARCHAR(500) DEFAULT NULL,
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_PAYMENTS_PAYMENT_NO` (`PAYMENT_NO`),
  KEY `IDX_PAYMENTS_ORDER_ID` (`ORDER_ID`),
  KEY `IDX_PAYMENTS_USER_ID` (`USER_ID`),
  KEY `IDX_PAYMENTS_STATUS` (`STATUS`),
  KEY `IDX_PAYMENTS_METHOD` (`METHOD`),
  KEY `IDX_PAYMENTS_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 文件表
-- ----------------------------
DROP TABLE IF EXISTS `FILES`;

CREATE TABLE `FILES` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FILENAME` VARCHAR(255) NOT NULL,
  `ORIGINAL_NAME` VARCHAR(255) NOT NULL,
  `FILE_PATH` VARCHAR(500) NOT NULL,
  `FILE_URL` VARCHAR(500) NOT NULL,
  `FILE_SIZE` BIGINT NOT NULL,
  `MIME_TYPE` VARCHAR(100) NOT NULL,
  `FILE_TYPE` VARCHAR(20) NOT NULL,
  `UPLOAD_USER_ID` BIGINT UNSIGNED DEFAULT NULL,
  `STORAGE_TYPE` VARCHAR(20) DEFAULT 'local',
  `STORAGE_PATH` VARCHAR(500) DEFAULT NULL,
  `HASH` VARCHAR(64) DEFAULT NULL,
  `WIDTH` INT DEFAULT NULL,
  `HEIGHT` INT DEFAULT NULL,
  `DURATION` INT DEFAULT NULL,
  `STATUS` VARCHAR(20) DEFAULT 'active',
  `DOWNLOAD_COUNT` BIGINT DEFAULT '0',
  `IS_PUBLIC` TINYINT(1) DEFAULT '1',
  `EXPIRED_AT` DATETIME(3) DEFAULT NULL,
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_FILES_UPLOAD_USER_ID` (`UPLOAD_USER_ID`),
  KEY `IDX_FILES_FILE_TYPE` (`FILE_TYPE`),
  KEY `IDX_FILES_STORAGE_TYPE` (`STORAGE_TYPE`),
  KEY `IDX_FILES_HASH` (`HASH`),
  KEY `IDX_FILES_STATUS` (`STATUS`),
  KEY `IDX_FILES_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ----------------------------
-- 初始数据插入
-- ----------------------------

-- 插入管理员用户
INSERT INTO `USERS` (
  `ID`,
  `USERNAME`,
  `EMAIL`,
  `PASSWORD`,
  `NICKNAME`,
  `ROLE`,
  `STATUS`,
  `CREATED_AT`,
  `UPDATED_AT`
) VALUES (
  1,
  'admin',
  'admin@example.com',
  '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
  '管理员',
  'admin',
  'active',
  NOW(),
  NOW()
),
(
  2,
  'testuser',
  'test@example.com',
  '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
  '测试用户',
  'user',
  'active',
  NOW(),
  NOW()
);

-- 插入商品分类
INSERT INTO `CATEGORIES` (
  `ID`,
  `NAME`,
  `SLUG`,
  `DESCRIPTION`,
  `PARENT_ID`,
  `LEVEL`,
  `IS_ACTIVE`,
  `SORT_ORDER`,
  `CREATED_AT`,
  `UPDATED_AT`
) VALUES (
  1,
  '数码电子',
  'electronics',
  '数码电子产品',
  0,
  1,
  1,
  1,
  NOW(),
  NOW()
),
(
  2,
  '服装鞋帽',
  'clothing',
  '服装鞋帽用品',
  0,
  1,
  1,
  2,
  NOW(),
  NOW()
),
(
  3,
  '家居生活',
  'home',
  '家居生活用品',
  0,
  1,
  1,
  3,
  NOW(),
  NOW()
),
(
  4,
  '运动户外',
  'sports',
  '运动户外用品',
  0,
  1,
  1,
  4,
  NOW(),
  NOW()
),
(
  5,
  '美妆护肤',
  'beauty',
  '美妆护肤产品',
  0,
  1,
  1,
  5,
  NOW(),
  NOW()
);

-- 插入示例商品
INSERT INTO `PRODUCTS` (
  `ID`,
  `NAME`,
  `SUB_TITLE`,
  `DESCRIPTION`,
  `CATEGORY_ID`,
  `BRAND_ID`,
  `MERCHANT_ID`,
  `PRICE`,
  `ORIGIN_PRICE`,
  `STOCK`,
  `SOLD_COUNT`,
  `STATUS`,
  `IS_HOT`,
  `IS_NEW`,
  `IS_RECOMMEND`,
  `RATING`,
  `RATING_COUNT`,
  `VIEW_COUNT`,
  `CREATED_AT`,
  `UPDATED_AT`
) VALUES (
  1,
  'iPhone 15 Pro Max 256GB 深空黑色',
  '搭载A17 Pro芯片，支持5G网络',
  '搭载A17 Pro芯片，支持5G网络，拥有强大的摄影系统和超长续航能力。采用钛金属设计，更轻更坚固。',
  1,
  1,
  1,
  8999.00,
  9999.00,
  50,
  1250,
  'active',
  1,
  1,
  1,
  4.80,
  856,
  12450,
  NOW(),
  NOW()
),
(
  2,
  'MacBook Pro 14英寸 M3芯片',
  '全新M3芯片，专业级性能',
  '全新M3芯片，14英寸Liquid Retina XDR显示屏，专业级性能，适合创意工作者。支持最新的macOS系统。',
  1,
  1,
  1,
  13999.00,
  15999.00,
  30,
  856,
  'active',
  1,
  0,
  1,
  4.90,
  642,
  8960,
  NOW(),
  NOW()
),
(
  3,
  'Nike Air Max 270 运动鞋',
  '经典Air Max气垫设计',
  '经典Air Max气垫设计，舒适透气，适合日常运动和休闲穿着。多种颜色可选，时尚百搭。',
  2,
  2,
  1,
  699.00,
  899.00,
  120,
  2340,
  'active',
  1,
  0,
  0,
  4.60,
  1856,
  15670,
  NOW(),
  NOW()
),
(
  4,
  'Sony WH-1000XM5 无线降噪耳机',
  '业界领先的降噪技术',
  '业界领先的降噪技术，30小时续航，高解析度音质，舒适佩戴。支持快速充电和多设备连接。',
  1,
  3,
  1,
  1999.00,
  2299.00,
  45,
  1456,
  'active',
  0,
  1,
  1,
  4.90,
  1234,
  9870,
  NOW(),
  NOW()
),
(
  5,
  'Adidas Ultraboost 22 跑步鞋',
  '专业跑步鞋，舒适缓震',
  '专业跑步鞋，采用Boost中底技术，提供卓越的能量回馈和舒适缓震体验。适合长距离跑步。',
  2,
  4,
  1,
  999.00,
  1199.00,
  80,
  987,
  'active',
  0,
  0,
  1,
  4.70,
  756,
  6540,
  NOW(),
  NOW()
);

-- 插入商品图片
INSERT INTO `PRODUCT_IMAGES` (
  `ID`,
  `PRODUCT_ID`,
  `URL`,
  `ALT`,
  `IS_MAIN`,
  `SORT_ORDER`,
  `CREATED_AT`,
  `UPDATED_AT`
) VALUES (
  1,
  1,
  'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400',
  'iPhone 15 Pro Max',
  1,
  1,
  NOW(),
  NOW()
),
(
  2,
  2,
  'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
  'MacBook Pro 14英寸',
  1,
  1,
  NOW(),
  NOW()
),
(
  3,
  3,
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
  'Nike Air Max 270',
  1,
  1,
  NOW(),
  NOW()
),
(
  4,
  4,
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
  'Sony WH-1000XM5',
  1,
  1,
  NOW(),
  NOW()
),
(
  5,
  5,
  'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
  'Adidas Ultraboost 22',
  1,
  1,
  NOW(),
  NOW()
);

-- 插入示例购物车
INSERT INTO `CARTS` (
  `ID`,
  `USER_ID`,
  `STATUS`,
  `ITEM_COUNT`,
  `TOTAL_QTY`,
  `TOTAL_AMOUNT`,
  `CREATED_AT`,
  `UPDATED_AT`
) VALUES (
  1,
  2,
  'active',
  2,
  2,
  10998.00,
  NOW(),
  NOW()
);

-- 插入购物车商品项
INSERT INTO `CART_ITEMS` (
  `ID`,
  `CART_ID`,
  `PRODUCT_ID`,
  `QUANTITY`,
  `PRICE`,
  `PRODUCT_NAME`,
  `PRODUCT_IMAGE`,
  `SELECTED`,
  `STATUS`,
  `CREATED_AT`,
  `UPDATED_AT`
) VALUES (
  1,
  1,
  1,
  1,
  8999.00,
  'iPhone 15 Pro Max 256GB 深空黑色',
  'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400',
  1,
  'normal',
  NOW(),
  NOW()
),
(
  2,
  1,
  4,
  1,
  1999.00,
  'Sony WH-1000XM5 无线降噪耳机',
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
  1,
  'normal',
  NOW(),
  NOW()
);

-- ----------------------------
-- 地址表
-- ----------------------------
DROP TABLE IF EXISTS `ADDRESSES`;

CREATE TABLE `ADDRESSES` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `RECEIVER_NAME` VARCHAR(50) NOT NULL COMMENT '收货人姓名',
  `RECEIVER_PHONE` VARCHAR(20) NOT NULL COMMENT '收货人电话',
  `PROVINCE` VARCHAR(50) NOT NULL COMMENT '省份',
  `CITY` VARCHAR(50) NOT NULL COMMENT '城市',
  `DISTRICT` VARCHAR(50) NOT NULL COMMENT '区/县',
  `DETAIL_ADDRESS` VARCHAR(200) NOT NULL COMMENT '详细地址',
  `POSTAL_CODE` VARCHAR(10) DEFAULT NULL COMMENT '邮政编码',
  `IS_DEFAULT` TINYINT(1) DEFAULT '0' COMMENT '是否默认地址',
  `ADDRESS_TYPE` ENUM('home', 'company', 'other') DEFAULT 'home' COMMENT '地址类型',
  `CREATED_AT` DATETIME(3) DEFAULT NULL,
  `UPDATED_AT` DATETIME(3) DEFAULT NULL,
  `DELETED_AT` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_ADDRESSES_USER_ID` (`USER_ID`),
  KEY `IDX_ADDRESSES_IS_DEFAULT` (`IS_DEFAULT`),
  KEY `IDX_ADDRESSES_DELETED_AT` (`DELETED_AT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI COMMENT='用户地址表';

-- ----------------------------
-- 地址表示例数据
-- ----------------------------
INSERT INTO `ADDRESSES` (`ID`, `USER_ID`, `RECEIVER_NAME`, `RECEIVER_PHONE`, `PROVINCE`, `CITY`, `DISTRICT`, `DETAIL_ADDRESS`, `POSTAL_CODE`, `IS_DEFAULT`, `ADDRESS_TYPE`, `CREATED_AT`, `UPDATED_AT`) VALUES
(
  1,
  1,
  '张三',
  '13800138000',
  '广东省',
  '深圳市',
  '南山区',
  '科技园南区深南大道10000号',
  '518000',
  1,
  'home',
  NOW(),
  NOW()
),
(
  2,
  1,
  '张三',
  '13800138000',
  '广东省',
  '深圳市',
  '福田区',
  '华强北街道华强北路1000号',
  '518000',
  0,
  'company',
  NOW(),
  NOW()
);

SET FOREIGN_KEY_CHECKS = 1;